from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field


class VoucherOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    voucher_number: str
    voucher_date: date
    expense_date: date
    department: str
    expense_title: str
    expense_category: str | None
    expense_description: str | None
    amount: float
    employee_id: int
    employee_name: str | None
    employee_signature: str | None
    status: str
    director_signature: str | None
    approval_date: datetime | None
    rejection_reason: str | None
    created_at: datetime | None
    updated_at: datetime | None


class RejectInput(BaseModel):
    # The director must explain WHY the voucher is rejected
    rejection_reason: str = Field(min_length=1, max_length=1000)


class VoucherCreate(BaseModel):
    # voucher_number and voucher_date are generated by the server,
    # so the client does not send them
    department: str = Field(min_length=1, max_length=100)
    expense_title: str = Field(min_length=1, max_length=150)
    expense_category: str | None = Field(default=None, max_length=100)
    expense_description: str | None = None
    expense_date: date
    amount: float = Field(gt=0)


class VoucherUpdate(BaseModel):
    # All fields optional: only the ones the client sends are updated
    department: str | None = Field(default=None, min_length=1, max_length=100)
    expense_title: str | None = Field(default=None, min_length=1, max_length=150)
    expense_category: str | None = Field(default=None, max_length=100)
    expense_description: str | None = None
    expense_date: date | None = None
    amount: float | None = Field(default=None, gt=0)
